name: Backend CI

on: [push]

env:
  DB_HOST: database
  DB_PORT: 5432
  DB_USER: root
  DB_PASSWORD: root
  DB_NAME: petcare
  NODE_ENV: test

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: petcare
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20
        cache: 'npm'
        cache-dependency-path: 'backend/package-lock.json'
    
    - name: Install dependencies
      working-directory: ./backend
      run: npm ci
      
    - name: Run production build
      working-directory: ./backend
      run: npm run build


  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      packages: write  # Required to push to GHCR
      contents: read   # Required to checkout code
    
    steps:
      - uses: actions/checkout@v4
      
      # Login to GitHub Container Registry (no credentials needed)
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}  # Automatically available in actions
      
      - name: Build and push to GHCR
        working-directory: ./backend
        run: |
          # Get repository owner/name (converts to lowercase)
          REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          
          # Build with two tags: latest and git SHA
          docker build \
            -t ghcr.io/$REPO_NAME/backend:latest \
            -t ghcr.io/$REPO_NAME/backend:${{ github.sha }} \
            -f Dockerfile.prod .
          
          # Push both tags
          docker push ghcr.io/$REPO_NAME/backend:latest
          docker push ghcr.io/$REPO_NAME/backend:${{ github.sha }}