name: PetCare Build Pipeline

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json
    
    - name: Install Backend Dependencies
      working-directory: ./backend
      run: npm ci
    
    - name: Build Backend
      working-directory: ./backend
      run: npm run build
    
    - name: Archive Backend Build
      uses: actions/upload-artifact@v4
      with:
        name: backend-build
        path: backend/dist
        retention-days: 5

  build-frontend:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    
    - name: Install Frontend Dependencies
      working-directory: ./frontend
      run: npm ci
    
    - name: Build Frontend
      working-directory: ./frontend
      run: npm run build
    
    - name: Archive Frontend Build
      uses: actions/upload-artifact@v4
      with:
        name: frontend-build
        path: frontend/www
        retention-days: 5

  build-model:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
    
    - name: Install dependencies
      working-directory: ./Model
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Verify Model Package
      working-directory: ./Model
      run: |
        # Check if the app can be imported without errors
        python -c "import app"
    
    - name: Archive Model Code
      uses: actions/upload-artifact@v4
      with:
        name: model-package
        path: |
          Model/app
          Model/run.py
          Model/requirements.txt
        retention-days: 5