name: PetCare Model CI Pipeline

on:
  push:
    branches: [ main, master, develop ]
    paths:
      - 'Model/**'
  pull_request:
    branches: [ main, master, develop ]
    paths:
      - 'Model/**'

jobs:
  model-test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: petcare_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
    
    - name: Install dependencies
      working-directory: ./Model
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov flake8
        pip install -r requirements.txt
    
    - name: Lint with flake8
      working-directory: ./Model
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Test with pytest
      working-directory: ./Model
      run: |
        pytest --cov=app
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/petcare_test
        FLASK_ENV: testing